export const SAVE_MOVIE_TITLE = "SAVE_MOVIE_TITLE";

export const FETCH_MOVIE_INIT = "FETCH_MOVIE_INIT";
export const FETCH_MOVIE_SUCCESS = "FETCH_MOVIE_SUCCESS";
export const FETCH_MOVIE_ERROR = "ERROR";

export const ADD_MOVIE = "ADD_MOVIE";
export const REMOVE_MOVIE = "REMOVE_MOVIE";
